# From online public registries example
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    installation: online
spec:
  project: default
  source:
    # replace with the actual registry
    repoURL: https://github.com/cbeti-ionos/crossplane-demo.git
    path: cluster/crossplane
    targetRevision: HEAD
    helm:
      valueFiles:
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
